### PR TITLE
Add Upstart as an alternative to runit

### PR DESCRIPTION
**Pull request by davidgiesberg**

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@davidgiesberg thanks for contributing this! I’ll test it out as I have a chance, and if it works well, merge it in & cut a new release.

**Comment by davidgiesberg** [comment]
@jeffbyrnes Great, thanks so much!

**Comment by williamsjj** [comment]
Realizing the horse has left the barn on this...runit seems like the most agnostic way to run Exhibitor right now. Especially with Ubuntu dumping Upstart for systemd in 16.04.

**Comment by jeffbyrnes** [comment]
@williamsjj true, though folks will keep using 12.04 & 14.04 for some time.

**Pull request merged**
