### PR TITLE
Fix ownership of exhibitor jar to node[:exhibitor][:user] when using …

### PR DESCRIPTION
**Pull request by BCcjeris**
…download provisioning method

### CODE REVIEW

**Comment by BCcjeris** [comment]
This change seems to be required to make a non-root setting of `node[:exhibitor][:user]` effective when downloading rather than building Exhibitor; otherwise the Exhibitor jar is owned by `root` and not readable by `node[:exhibitor][:user]`, so the service cannot be started.

**Comment by jakedavis** [comment]
+1, thanks.

**Comment by jeffbyrnes** [comment]
@BCcjeris as a request for the future, in pull requests, would you please leave off bumping version numbers? Typical pattern is to do that when a new release is cut, along with writing up some release notes, etc.

Speaking of which, unless there’s an objection, I’m gonna get one of those out the door.

**Comment by jeffbyrnes** [comment]
Shipped with v0.5.0 to Supermarket.

**Pull request merged**
