### PR TITLE
LWRP only check

### PR DESCRIPTION
**Pull request by paulysullivan**
addition of lwrp only check, to allow utilizing LWRP functions without full exhibitor install

### CODE REVIEW

**Comment by jakedavis** [comment]
Hey @paulysullivan, I'm not sure about this change. Can't you just not call the default recipe? I might be missing something :) let me know if I am, thanks!

**Comment by paulysullivan** [comment]
I am using several mdsol cookbooks (https://github.com/mdsol/marathon_cookbook for example), which utilize your cookbooks LWRP functions for exhibitor auto discovery of zookeeper instances.

The default recipe installs zookeeper and exhibitor, which is not always desired, as there are dedicated systems in my environment which provide this function. In a test situation, where all services are ran locally, this is perfectly fine and good, but doesn't scale once you begin to piece the services out.

Alternatively another suggestion may be a blank or minimal recipe, which allows the LWRP functions to be continued to be used, without manipulating the system.

Thanks :)

**Comment by jakedavis** [comment]
So is the wish just to avoid the `zookeeper::default` call? Because if so we could just add a:

``` ruby
include_recipe 'zookeeper::default' if node[:exhibitor][:install_zookeeper] == true
```

Or something like this. The early return feels like a funky way to do it IMO. If all you want is access to the LWRPs, you should be able to just `depends` on this cookbook without including any recipes. I still might be misunderstanding the use-case a bit :)

**Comment by paulysullivan** [comment]
I was trying to avoid updating several cookbooks which recommend, not require, exhibitor. 

I see your point however, as the return can be confusing. I'll pursue that instead or maintain a fork. 

Thanks for your time.

**Comment by jakedavis** [comment]
Of course! Feel free to reopen if you think we can work something in to help out :)

**Pull request closed without merging**
