### PR TITLE
update to exhibitor 1.5.5, update gradle, build.gradle, and build command

### PR DESCRIPTION
**Pull request by lancehudson**
Updated to default to exhibitor 1.5.5.
Also Upgraded Gradle to 2.4 (needed newer version for new build file. I think 1.7 or higher is required).
Updated to new build.gradle file from NetFlix/Exhibitor and switched to the shadowJar command instead.

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@lancehudson love the upgrade to Exhibitor 1.5.5, but I’m curious about all the `shadow` stuff. I’m not much of a Java dev, so please forgive my ignorance.

**Comment by lancehudson** [comment]
nor me, my understanding is that shadowJar is how they build a jar including all of the dependencies. I quite literally copied their build file from https://github.com/Netflix/exhibitor/wiki/Building-Exhibitor#gradle

**Comment by jeffbyrnes** [comment]
In that case, :+1:

However, I'm off on holiday for two weeks starting… now, so it'll either have to wait, or maybe @jakedavis will pick this up. Cheers!

**Comment by jakedavis** [comment]
I can take a look here in awhile hopefully; busy day but will try to get to it before EOD :)

**Comment by jakedavis** [comment]
Well, I admit it's mostly opaque to me what's happening. Since it's the official build script, it probably makes plenty of sense. Kinda wish the Gradle bump was independent but that's aight.

Thank you @lancehudson!

**Comment by jeffbyrnes** [comment]
Shipped with v0.5.0 to Supermarket.

**Pull request merged**
